//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotification
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeetingQueue
    {
        public int MeetingQueueId { get; set; }
        public decimal Sequence { get; set; }
        public int PersonnelId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public int MeetingQueueStatusId { get; set; }
        public byte[] ModifiedStamp { get; set; }
        public int MeetingQueueCategoryId { get; set; }
        public int PercentCompleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> CalledDate { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public int EstimatedMinutes { get; set; }
        public int MeetingUrgencyId { get; set; }
        public Nullable<int> MeetingQueueSubCategoryId { get; set; }
        public Nullable<int> FileIDNo { get; set; }
        public Nullable<System.DateTime> QueueDeadline { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> PreviousMeetingQueueStatusId { get; set; }
        public Nullable<int> LeIdNo { get; set; }
        public Nullable<int> FileCompId { get; set; }
        public Nullable<int> AssignedTo { get; set; }
    }
}
